openapi: 3.0.0
info:
  title: Sample API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
security:
  - Bearer: []
paths:
  /item:
    get: 
      summary: List all items.
      operationId: getItems
      description: Lists all the items.
      responses: 
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: 
                  $ref: "#/components/schemas/item"
  /item/{id}:
    get:
      summary: Returns an item.
      operationId: getItem
      description: Get an item
      parameters: 
        - name: id
          in: path
          required: true
          description: Id of the item
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/item"
components:
  schemas:
    item:
      type: object
      properties: 
        bad:
          type: object
          properties:
            modelRef:
              type: object
              properties:
                id:
                  type: string
        good1:
          type: object
          properties:
            modelref:
              type: object
              properties:
                id:
                  type: string
        good2:
          type: object
          properties:
            modelRe:
              type: object
              properties:
                id:
                  type: string
        
  securitySchemes:
    Bearer:
      type: http
      scheme: bearer
      bearerFormat: AccessToken
